### ISSUE TITLE
When paused, timer shows total time

### ISSUE THREAD

**Issue by MrMcX** [ubilab-escape/environment#2]

**Comment by voelkerb** [comment]
Check if it is your gametime or the default gametime hardcoded in the Timer

**Comment by MrMcX** [comment]
We did, the topic `1/gameTime_in_sec` recieves nothing while paused.

**Comment by voelkerb** [comment]
so it is a problem of the timer code, I guess

**Comment by Jybs** [comment]
In fact, this functions start/stop/reset where developed while the timer itself counted down. Since it only read the value `1/gameTime_in_sec`, it does nothing else as printing it.
I check the code, and see that start/stop are useless, as the setted variable are never read.
Only reset function reset the timer to the setted gameduration. This is overwrite directly at the first `1/gameTime_in_sec`

**Comment by MrMcX** [comment]
Fixed by ubilab-escape/operator@3bc191b
